name: Test Secrets

on: [push]

jobs:
  secret-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Echo Secret (Nicht empfohlen für echte Secrets!)
        run: echo "Das Secret ist ${{ secrets.MY_SECRET_KEY }}"
